### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by mquandalle** [publicodes/language-server#11]
Hi, thank you for working on the publicodes language server!

I tried using it on the following publicodes file: https://github.com/mquandalle/mesaidesvelo/blob/master/src/aides.yaml

But I get the following output in VSCode : 

```
[Error] Server initialization failed.
[Error] Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by EmileRolley** [comment]
Thanks for your feedback. Could you show the full error message please?

> [!NOTE]
> You will need to rename your `*.yaml` files into `*.publicodes` in order to activate the extension.

**Comment by mquandalle** [comment]
The console is filled with minified code from `node:electron` I can't find any more relevant error message

**Comment by EmileRolley** [comment]
I think it's now fixed with the prebuilds native node modules packages in https://github.com/publicodes/tree-sitter-publicodes/releases/tag/v0.1.3.
