### ISSUE TITLE
Read `.publicodes.yaml` files same as `.publicodes`

### ISSUE THREAD

**Issue by fmata** [publicodes/language-server#15]
Hello,
We renamed all `.publicodes` rules files to `.publicodes.yaml` to be interoperable with my team which uses VS Code and others IDE as IntelliJ (Webstorm etc).
If the extension can understand `.publicodes` and `.publicodes.yaml` every developer will be happy :)

**Comment by EmileRolley** [comment]
Hi, isn't it possible to configure Intellij IDEs to consider `.publicodes` files as YAML files? Otherwise, it seems fair to me to support `.publicodes.yaml` I'll look at it :) 

(Did you manage to run the VSCode extension? What's your OS?)

**Comment by fmata** [comment]
Sure we can with IntelliJ but rules are plain YAML, I suppose the need for a custom extension is only for the VS Code extension. When we use "dumb" text editor (Vim, Emacs...) it guess the content by the extension and it's painfull to add a specific handling.
